<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Daftar Pengawas Control Room yang dimonitor
|--------------------------------------------------------------------------
|
| Dipakai /control-room/pengawas (Monitoring Pengawas). Kode site mengikuti
| App\Enums\ControlRoomSiteCode. Tambah / hapus orang cukup di sini.
| Format baris: [SID, kode site, nama].
*/

return [
    'list' => [
        ['KAPYD', 'BMO1', 'RIZA RAHMADI'],
        ['NCKPF', 'BMO1', 'RUKHMAN ABIDIN'],
        ['TRW8F', 'GMO', 'RANDI .'],
        ['YH00S', 'SMO', 'SONI .'],
        ['SEZ13', 'SMO', 'MIRSA DAYAN PASOLON'],
        ['WKYUS', 'BMO1', 'HERI SETIYAWAN'],
        ['P7GKP', 'LMO', 'GALATIA PRAKOSO KRISTIANTORO'],
        ['H5UBW', 'BMO2', 'MASRUR ABDUL AZIS'],
        ['24KLA', 'BMO2', 'PUPUT WINARKO'],
        ['SBQ2W', 'BMO3', 'GALIB KUSUMA PUTRA'],
        ['QTVJ3', 'BMO3', 'FAIZAL ARBAIN'],
        ['04FA0', 'GMO', 'WARYANTO .'],
        ['NGIZZ', 'BMO2', 'AHMAD NORODIN'],
        ['P3BUT', 'BMO2', 'MUH AQIL FIKHRY NUR YAASIN'],
        ['2RFSV', 'BMO2', 'DANI ADITYA HERWANTO'],
        ['PUOEP', 'BMO1', 'DANI SUSIANTO'],
        ['5V8CP', 'BMO1', 'WISNU AGUNG RAMADHANI'],
        ['LZFEO', 'BMO1', 'A ALFIN NILAN SAPUTRO'],
        ['QQLTI', 'BMO1', 'IRON .'],
        ['I9NIL', 'GMO', 'KAROLUS KALMON'],
        ['5X1LB', 'SMO', 'M LULUS MISBAH AL HAKIM'],
        ['WJVXL', 'SMO', 'ANAS SYAHRULLAH'],
        ['Z0GGV', 'BMO3', 'ANAKTA HARTANTA SEBAYANG'],
        ['2412R', 'BMO3', 'ARI FADLI'],
        ['EKAHQ', 'SMO', 'RAMADHANDY ARYA PRADANA'],
        ['FLZ9O', 'LMO', 'LAHARDI SULAKSONO PUTRO'],
        ['D0NL2', 'LMO', 'BOBBY FROBEL GULTOM'],
        ['1HMK1', 'BMO2', 'PARYANTO'],
        ['55ED8', 'BMO2', 'ANGGA ANGGRIYANTO'],
        ['BMK3N', 'GMO', 'RIONAIS BISAID'],
        ['KWXDD', 'LMO', 'YOHAN .'],
        ['GQNQI', 'BMO1', 'MUH AZWAR ANWAR'],
        ['QACRX', 'BMO2', 'SAHRUL RIFA I'],
        ['RNEZJ', 'GMO', 'IBRAHIM FATHAHILLAH HIZBUL ISLAM'],
        ['XWHG7', 'BMO2', 'ANJAR DONY PRASETYO'],
        ['YCB55', 'BMO1', 'HELFID SAMAD'],
        ['QH8RU', 'BMO2', 'ANDY PURNOMO'],
        ['LDQ2H', 'BMO3', 'RYDANI AFFANDHI SAPUTRA'],
        ['6TS9P', 'LMO', 'ARMAWAN .'],
        ['X0O95', 'BMO1', 'MUH JUNON ODE'],
        ['46SU6', 'BMO2', 'SUDARSONO .'],
        ['FGI0D', 'BMO1', 'OKTOVIANUS .'],
        ['LR9WU', 'SMO', 'LEGA CAHYA SAPUTRA'],
        ['RDZXZ', 'BMO2', 'NASIR SOLEHFUDIN'],
        ['E91J6', 'SMO', 'ARIS ACHDIAT'],
        ['K39JP', 'GMO', 'ADITIYA RAMADAN'],
        ['N019F', 'LMO', 'BUDI FEBRIANTO'],
        ['1FIB2', 'BMO1', 'RIFKY AKBAR'],
        ['ZR44D', 'BMO1', 'SYAMSU TABRICH APLATUN'],
        ['TAPH0', 'BMO3', 'SAMRI RUSIADI'],
        ['DI2GM', 'SMO', 'MUH FAISAL RAHMAN'],
        ['MD28I', 'GMO', 'ERI SETYAWAN'],
        ['J6YEH', 'SMO', 'DANIEL JONDRIS LUMBAN RAJA'],
        ['8J0Q6', 'LMO', 'KHOIRIL ANWAR'],
        ['00LQM', 'SMO', 'SANTOS MURTOPO'],
        ['A8TDO', 'BMO1', 'MUHAMMAD PADLI AKBAR'],
        ['ZIATX', 'GMO', 'AZWAN .'],
        ['4OZM1', 'SMO', 'ADE KURNIAWAN YUNUS'],
        ['3N96H', 'BMO2', 'FAJAR DWI PAMBUDI'],
        ['XTRLN', 'BMO2', 'PARYANTO .'],
        ['S5C12', 'LMO', 'ZULKIPLI .'],
        ['URLU1', 'LMO', 'IHANG PANJI PUSAKA'],
        ['H2XKC', 'GMO', 'AZZANI ZAKA WALI'],
        ['Y8DIZ', 'BMO3', 'RAGIL ADJI PRABANDARU'],
        ['8B5OP', 'BMO1', 'SUGANDA SIMAMORA'],
        ['9AOLX', 'SMO', 'SUMAI PURWOKO'],
        ['7W3BQ', 'SMO', 'MUHAMMAD YUSRAN AMIR'],
        ['WF0QC', 'LMO', 'MUHAMMAD NAUFAL NABIL'],
        ['WXV33', 'BMO2', 'CHRISTIE GRATIA PRASASTI PRIYAMBODO'],
        ['LA44A', 'BMO2', 'DONI WIDIYANTO'],
        ['VX27W', 'BMO2', 'ROBI SAPUTRA'],
        ['P2RK6', 'BMO2', 'BUDHI WAHYONO'],
        ['Z7JDQ', 'BMO1', 'WELLY ARTO'],
        ['WSQ2A', 'BMO1', 'DANI RAKASIWI'],
        ['CZK8I', 'GMO', 'RONI ROMANSAH'],
        ['1HJCZ', 'BMO1', 'LORENSIUS TULAK BELANTARA'],
        ['WAIH6', 'BMO2', 'NAUFAL RAFID RIZQULLAH'],
        ['J9NFI', 'BMO2', 'FENDI TEGUH RAHARJO'],
        ['JKL6M', 'BMO2', 'KURNIAWAN .'],
        ['NWLNH', 'BMO2', 'WAHYU AMARTA'],
        ['TZ1XP', 'LMO', 'RICKIK SUTRISNO'],
        ['7B5MC', 'LMO', 'FAISHAL AMINURAHMAN'],
        ['A8NN7', 'SMO', 'DWIYAN ADI WIJAYA'],
        ['02H7Y', 'SMO', 'ANNAS .'],
        ['6M9L7', 'GMO', 'MUHAMMAD MUKTAR MUKTI'],
        ['K10GY', 'LMO', 'M. RIDWANSYAH'],
        ['42OWP', 'BMO1', 'HERMAN SABRI'],
        ['ZWT83', 'BMO1', 'HERMAWAN APRIYADI'],
        ['0ERSP', 'BMO1', 'FADHLI JULIA HIMAWAN'],
        ['H084F', 'EKSPLORASI', 'MUHAMAD KOCAL'],
        ['B0RW5', 'EKSPLORASI', 'TASWADI .'],
        ['EN8QU', 'LMO', 'FIKRI HAIKAL S'],
        ['1WH7Z', 'SMO', 'ANTON WIBOWO'],
        ['AA5B7', 'BMO2', 'MOHAMAD REFO ADITYANSYAH'],
        ['HAHIT', 'BMO2', 'BAYU SAPTO AJI'],
        ['CE5YK', 'GMO', 'SALSABIELA FIRDAUSI'],
        ['7AEXF', 'BMO1', 'SHENDY AFRIYAN PERMANA'],
        ['GVXLA', 'BMO1', 'AGUNG PRASETYO'],
        ['7Y4XC', 'BMO1', 'FATHUDDIN .'],
        ['664YX', 'GMO', 'CORNELIUS .'],
        ['V6LDR', 'BMO1', 'DAVID ALDO WIDJAYA'],
        ['47ZMC', 'BMO1', 'HALFIC RISALDI'],
        ['QVFTL', 'LMO', 'RAHMAT HIDAYAT'],
        ['6JMHD', 'HO', 'RIZKY SAPUTRA'],
        ['XL6QP', 'BMO1', 'AHMAD NUROKHIM'],
        ['YYY9P', 'SMO', 'UJANG FERNANDES GUCIANO'],
        ['C1KVF', 'BMO2', 'ACHMAD SANJALI'],
        ['SOJK4', 'BMO2', 'RISTANTO .'],
        ['658AZ', 'BMO1', 'RAIFA RADITYA RANGSANG'],
        ['PXBY5', 'GMO', 'RAFIF MAHRUS KHALIK'],
        ['JQ137', 'BMO1', 'YUNIAR IRAWAN'],
        ['ZU23S', 'BMO1', 'RAY VANDIRGA'],
        ['85ZWR', 'BMO1', 'MUHAMMAD PARIS ALPARIZI'],
        ['3OJXP', 'HO', 'EZA ERDY IANDRA'],
        ['BCVEE', 'EKSPLORASI', 'MUHAMMAD SABIRUSSALAM'],
        ['4LRN0', 'GMO', 'ANASTASIA ANDARI ROEFITA RIABRATA'],
        ['JM7A6', 'BMO2', 'AGUS MANGUN DIHARJO'],
        ['RF41P', 'BMO2', 'ARDIKA SUGIARTO'],
        ['KKPG6', 'BMO1', 'ANASTASIA NELY BALABA'],
        ['U85TE', 'LMO', 'ARIS .'],
        ['NU42S', 'BMO2', 'EDI SUSILO'],
        ['PD9B8', 'BMO1', 'BORIS CARLISON JHEFRY GHETA'],
        ['YP6UG', 'BMO1', 'WENDY SUSTIAWAN'],
        ['6DM84', 'LMO', 'MANAMPIN SAMOSIR'],
        ['H2V4R', 'BMO1', 'EKA TRISNA SUYUDI'],
        ['OT0N3', 'LMO', 'ANGGA PRASETYA UTAMA'],
        ['X20HC', 'GMO', 'MUHAMMAD MAWAHIBUL FADLI'],
        ['BYBCI', 'LMO', 'BADRUN ALAMSYAH'],
        ['HLKPC', 'HO', 'ANDI ASWAR ABDULLAH'],
        ['MA1WR', 'GMO', 'IRFAN ABRINANTO'],
        ['H8DV3', 'BMO1', 'YUNAN HELMI'],
        ['RNEXB', 'BMO1', 'HEPI ABDIANTO'],
        ['B0C8S', 'BMO2', 'RAKHMAN WARDANA'],
        ['GUKT3', 'BMO1', 'AGUNG KUSRIANJAR'],
        ['HNPBX', 'LMO', 'ASBI'],
        ['MWHA0', 'LMO', 'YUSTIKA MARSELINO'],
        ['02PET', 'GMO', 'GLORIUS EDWIN NATANAEL'],
        ['T57OO', 'HO', 'FAISAL RIZA'],
        ['6Q6HV', 'LMO', 'PRISCO HIZKIA SADEWA BUNTAR'],
        ['NWQ3N', 'LMO', 'REYNALDI ALFAREZIRAMANDA'],
        ['FPWIQ', 'BMO2', 'WAHYU PRATAMA'],
        ['0KHT9', 'BMO1', 'YANDI APRIYAN'],
        ['C2UA6', 'EKSPLORASI', 'BAYU RAMADHAN PUTRANIKO'],
        ['HXKB6', 'LMO', 'GILANG NANDA SAGITA'],
        ['MYRG9', 'GMO', 'BRAVIN MANDALA CHRISNA'],
        ['SPY11', 'SMO', 'YEREMIAS MBABHO'],
        ['TQ5RY', 'LMO', 'GEDE DEDI PEPRIANA'],
        ['F954R', 'LMO', 'ANDI SEPTI ELIYA NINGSIH'],
        ['WE0L6', 'SMO', 'DEFRI FAJAR'],
        ['D7KBS', 'BMO2', 'ANDI SUWANTO'],
        ['MMR5K', 'BMO2', 'DIYO DARMA PRATAMA'],
        ['3CSLR', 'LMO', 'NAUFAL HANIF ANDIRA'],
        ['IK2BN', 'GMO', 'SISWANTO .'],
        ['GF89S', 'BMO1', 'FERIANSYAH .'],
        ['WPRA4', 'GMO', 'SUTRISNO RAHIM'],
        ['FJ2GN', 'BMO2', 'SURYA WIRAHADIKUSUMA SH'],
        ['3NYP5', 'BMO3', 'DENDY HERNAWAN ANDUNG'],
        ['H1VXC', 'GMO', 'ANITA CHRISTIANI SIANTURI'],
        ['8MWVX', 'GMO', 'FADRA ADITIA PRADANA'],
        ['1Q6RO', 'BMO1', 'INO SEBELAS'],
        ['DV9PH', 'BMO2', 'ADITYASRIZKI PRATAMA'],
        ['RHZF8', 'GMO', 'NAJMUDIN .'],
        ['M6DM5', 'LMO', 'ARDI ISDAR PRASETYANA'],
        ['Y7PDW', 'HO', 'ANTONIUS PADUANSI'],
        ['JCSTE', 'GMO', 'BAYU AJI WIRANATA'],
        ['EUPAF', 'EKSPLORASI', 'REZKY ILHAMY'],
        ['K9YU2', 'LMO', 'HERI GUNAWAN'],
        ['GMPEG', 'HO', 'EKO RUSMIDIYANTO'],
        ['SFC88', 'LMO', 'INDRA PRASETYO'],
        ['Y90E0', 'BMO1', 'JAYA EKPENDI'],
        ['VJ3YM', 'BMO2', 'MOHRIAL .'],
        ['5W3N0', 'BMO2', 'MOHAMAD THOYIB ROSIDI'],
        ['J2AY1', 'BMO2', 'HERMAN LELEA'],
        ['KQ4GA', 'BMO2', 'GERALDO OKTAVIANUS SIGAR'],
        ['FVTZJ', 'LMO', 'GINSA SEVIAN GILANG PERMANA'],
        ['7NR5E', 'SMO', 'SUCIPTO .'],
        ['Z5POR', 'BMO1', 'ABDUL MALIK MAULANA'],
        ['YER9Z', 'BMO2', 'FITRIANI .'],
        ['T63HM', 'BMO1', 'BAYU INDRA JAYA'],
        ['LELI3', 'LMO', 'MUHSIN SUPRIADY'],
        ['GX1FN', 'BMO2', 'SETYA ADHI WIBOWO'],
        ['ECQ6I', 'BMO2', 'AGENG BUWANA'],
        ['TKMB5', 'LMO', 'QADARISNU TRISAKTI'],
        ['1CIZL', 'SMO', 'ANDRI ARTA WIMAHERDI'],
        ['JBFGA', 'LMO', 'ANDI SAPUTRA'],
        ['F9PGP', 'LMO', 'KRISTIYANTO .'],
        ['S3TOZ', 'BMO2', 'ANJA PRASETYO'],
        ['CW2GR', 'BMO2', 'SILVANUR ROMADHONI'],
        ['PR4IT', 'BMO2', 'MUHAMMAD DZUL ROKHIM'],
        ['T97O7', 'SMO', 'YOGI WIGUNA'],
        ['MOXT0', 'SMO', 'BUDI WAHYU NUGROHO'],
        ['PUVIJ', 'BMO1', 'ADI DARMAWAN'],
        ['3400F', 'BMO2', 'ADHITYA AL GHANI'],
        ['L8N06', 'BMO3', 'ADAM MALIK'],
        ['I0PQJ', 'BMO2', 'YAHYA HARYANTO'],
        ['93VXI', 'BMO2', 'SEPTIANT DWI CAHYO HENDARTO'],
        ['HF4ZI', 'BMO2', 'RIZKI RAHMAT HIDAYAT'],
        ['N01R6', 'LMO', 'SYAHRIAL NAULI NASUTION'],
        ['H7SJQ', 'LMO', 'JAKA HASTA TILAR'],
        ['0YA8U', 'BMO1', 'MISYONO .'],
        ['UFWEH', 'SMO', 'ALVIRKHAN HAFIDZ ARAFATH'],
        ['TCA27', 'BMO1', 'JUFRI MUSTARI'],
        ['K9ORE', 'BMO1', 'DWI KURNIAWAN AHMAD'],
        ['7CA11', 'BMO2', 'VICTOR KAMBEY'],
        ['V0EM4', 'BMO1', 'ARIS HADI SUMARYONO'],
        ['B16Y6', 'LMO', 'AL FIANSYAH INDARDI AMIRIN'],
        ['UATTD', 'LMO', 'ACHMAD SYAROFI'],
        ['L3OJK', 'MARINE', 'RICHARD CHUA'],
        ['3C4E7', 'SMO', 'WAGEANTONO .'],
        ['ODJ39', 'BMO1', 'ADIL MURSIDI GORAN'],
        ['9GOX8', 'BMO2', 'AZWAR THAMRIN'],
        ['RC73L', 'GMO', 'DIDIK MIHARJA'],
        ['XQBKF', 'GMO', 'RAKHMAD HIDAYAT'],
        ['ACU47', 'BMO1', 'MAURICE AHMAD'],
        ['NMOY9', 'MARINE', 'MUHAMMAD ZUL FAJAR'],
        ['GOVMV', 'GMO', 'JASRIANSYAH .'],
        ['0RTQ8', 'LMO', 'ABDUL RIFAI'],
        ['JOLHT', 'LMO', 'AHMAD FAQIH MAHFUZ'],
        ['LO082', 'GMO', 'RIO SETIAWAN'],
        ['YMIST', 'SMO', 'AFIF NUR ALIM'],
        ['6NL2E', 'BMO2', 'JUMIKO .'],
        ['1412N', 'GMO', 'FIVIN NURHAFIDZAH HALIM'],
        ['NDDM5', 'BMO2', 'LINTANG JANUAR P PUTRA'],
        ['T6RO5', 'BMO2', 'QORNUL MANAZIL S PD'],
        ['WQ0CD', 'LMO', 'AHMAD TITO RUSHARMANTO'],
        ['TNAUT', 'GMO', 'IKHWANUL MUSLIMIN'],
        ['ZAJ22', 'GMO', 'RICHAD RAHIM'],
        ['6MSZH', 'GMO', 'RANITA ASELINA SIMANUNGKALIT'],
        ['G02BL', 'BMO1', 'MACHYUDI .'],
        ['8GR5K', 'BMO1', 'SAYN ARMY ALBANI'],
        ['P7EIA', 'BMO1', 'YASSER ARAFAT'],
        ['5R9I3', 'BMO1', 'AJI MASYHADI'],
        ['NGT0W', 'GMO', 'WAHYU HIDAYAT'],
        ['U35IH', 'SMO', 'RUDI FEBRIADI'],
        ['24Z7V', 'LMO', 'DESSY NATASHA LUDE BR SIANTURI'],
        ['5F4J2', 'BMO1', 'MOCH HARDY WINARYO'],
        ['N5RK1', 'BMO2', 'WAHYU PRAMONO AJI'],
        ['PVW3O', 'BMO2', 'RIAN SULISTYO'],
        ['CH0R7', 'LMO', 'RAHMAD .'],
        ['8MDB5', 'BMO1', 'ALDO RAMADHAN PRANOTO'],
        ['SPMN3', 'BMO1', 'JAINUL FAHRIANTO'],
        ['8FEUD', 'LMO', 'FAHRUDDIN JAMIL'],
        ['LMM4E', 'GMO', 'MUHAMMAD RAHMATULLAH'],
        ['TPL6J', 'GMO', 'I KOMANG PASEK NUJAYA'],
        ['LL37K', 'GMO', 'NUGROHO GALIH PUSPITO'],
        ['3IKNI', 'GMO', 'ZULFANI .'],
        ['MDAHZ', 'EKSPLORASI', 'ARDAN WILDAN'],
        ['IK6GZ', 'BMO2', 'EDI WIYONO'],
        ['2USDY', 'SMO', 'SAEPUDIN DARMAWAN'],
    ],
];
