<?php

declare(strict_types=1);

/**
 * Mapping manual divisi BeWell (employee_profiles.divisi) → label grup kanonik.
 * Key = label yang tampil di filter/breakdown; value = daftar alias mentah (exact, case-insensitive).
 */
return [

    'HSE / OHS / SHE / QHSE' => [
        'OCCUPATIONAL HEALTH & SAFETY',
        'OCCUPATIONAL HEALTH & SAFETY DIVISION',
        'OHS',
        'HSE',
        'HSE Divisi',
        'HSE Division',
        'DEPT. HSE',
        'EHS DIVISION',
        'SHE',
        'SHE DIVISION',
        'SHE Division',
        'QHSE',
        'SAFETY, HEALTH , & ENVIRONMENT',
        'SYSTEM COMPLIANCE & ENVIRONMENT',
        'SYSTEM COMPLIANCE & ENVIRONMENT DIVISON',
        'SYSTEM COMPLIANCE DIVISION',
        'System & Compliance',
    ],

    'Operation / Operasional' => [
        'OPERATION',
        'Operation',
        'OPERATION DIVISION',
        'Operation Division',
        'Operation Department',
        'OPERASIONAL',
        'Operasional',
        'OPERATIONAL',
        'Operational',
        'OPR',
        'OPERATION & SUPPORT RELATION',
        'OPERATION & SUPPORT RELATION DIVISION',
        'OPERATION SUPPORT',
        'OPERATIONS SUPPORT DIVISION',
        'Operation Support',
        'Operation Support & Relation',
        'Operation Management',
        'Operational Project',
        'Operation & Supply Chain',
        'OPERATION & HSE DEPUTY DIRECTORATE',
        'OPERATION & HSE DIRECTORAT',
        'Operations & HSE Directorat',
        'OPR HSE & SUPPORT RELATION DEPUTY DIR',
        'PENANGGUNG JAWAB OPERASIONAL',
        'MINE OPERATION & SUPPORT',
        'MINE OPERATION & SUPPORT DIVISION',
        'MINE OPERATIONS & SUPPORT DIVISION',
        'Mine Support',
        'Mine Support Division',
    ],

    'Production / Produksi' => [
        'PRODUCTION',
        'PRODUCTION DEPARTMENT',
        'PRODUKSI',
        'Produksi',
        'Divisi Produksi',
        'MINING DIVISI',
    ],

    'Plant' => [
        'PLANT',
        'Plant',
        'PLANT DEPARTMENT',
        'Plant Division',
        'PLANT & FACILITY',
        'ADMIN PLANT',
        'FIXED PLANT MAINTENANCE',
    ],

    'General Service / HR / HCGS' => [
        'GENERAL SERVICE',
        'GENERAL SERVICE DIVISON',
        'GS Support Division',
        'HCGS',
        'HRGA',
        'HRGS',
        'HRGS DIRECTORATE',
        'HRGS DIVISION',
        'HRGS OPERATION DIVISION',
        'HR GA Division',
        'HR GS',
        'HR OPERATIONS DIVISION',
        'HR OPERATIONS UJB',
        'HR STRATEGIC & PLANNING DIVISION',
        'HUMAN CAPITAL',
        'HUMAN RESOURCES & GENERAL AFFAIRS',
        'Human Resources & General Affairs',
        'DEPT. HRD',
        'House Keeping Division',
        'PEOPLE JOURNEY DIVISION',
        'TALENT DEVELOPMNET',
        'MANAGEMENT DEVELOPMENT',
    ],

    'Logistik / SCM / Part' => [
        'LOGISTIC',
        'LOGISTICS',
        'LOGISTIK',
        'Logistic',
        'LOGISTIK & HRGA',
        'SCM',
        'PSCM',
        'CORPORATE PROCUREMENT SCM DIVISION',
        'CORPORATE PROCUREMENT STRATEGIC',
        'PROCUREMENT',
        'PART',
        'PART DIVISION',
    ],

    'Engineering / Technical' => [
        'ENGINEERING',
        'Engineering',
        'ENG',
        'TECHNICAL',
        'Technical & Operation',
        'TECHNICAL TRAINING DIVISION',
        'TECNICAL SUPPORT & VSAT',
        'ELECTRICAL',
        'CIVIL MECHANICAL ELECTRICAL [CME]',
        'FABRICATION WELDING',
        'FIRE AND GAS SYSTEM',
        'FIELD SERVICE AND WARRANTY',
        'Maintenance',
        'Maintenance Trailer',
        'FLEET',
        'MINE PLAN ENGINEERING',
        'MINE PLANNING & TECH. SERVICES DIVISION',
        'MINE PLANNING & TECHNICAL SERVICES DIVISION',
        'Mine Plan & Technical Services',
        'Mineplan & Technical Services',
    ],

    'Finance / Accounting' => [
        'ACCOUNTING FINANCE',
        'FINANCE',
        'FINANCIAL PLANNING & ANALYSIS DIVISION',
        'FINANCIAL REPORTING & ACC. DIVISION',
        'FINANCIAL REPORTING & ACCOUNTING DIVISION',
        'TREASURY DIVISION',
        'TAX,CUSTOMS & GOV. LIABILITIES OPS DIVISON',
    ],

    'IT / Telco' => [
        'IT',
        'INFORMATION & TECHNOLOGY',
        'IT INFRASTRUCTURE & OPERATION DIVISION',
        'IT INFRASTRUCTURE & OPERATIONS',
        'IT INFRASTRUCTURE DIVISION',
        'IT Project',
        'DATA ANALYST',
        'TELCO',
        'Network Project Implementation',
        'BUILDING AND NETWORK SOLUTION',
    ],

    'Marketing / Marine / Commercial' => [
        'MARKETING',
        'Marketing',
        'MARKETING DIVISION',
        'MARKETING & MARINE DIVISION',
        'MARINE',
        'MARINE DIVISI',
        'MARRINE',
        'MOORING',
        'COMMERCIAL DIVISION',
        'GMO COMMERCIAL & OPS IMPROVEMENT',
        'GMO COMMERCIAL & OPS IMPROVEMENT DIV',
        'GMO COMMERCIAL & OPS IMPROVEMENT DIVISION',
    ],

    'Project / Construction' => [
        'PROJECT',
        'Project Management',
        'PRO',
        'CONSTRUCTION',
        'DEPT. CONSTRUCTION',
        'INFRASTRUCTURE',
        'Road Maintenance',
    ],

    'Corporate / Legal / CSR' => [
        'CORPORATE SECRETARY',
        'CORPORATE SECRETARY DIVISION',
        'LEGAL DIRECTORAT',
        'LEGAL MINING',
        'LEGAL MINING DIVISION',
        'LICENSE & CORP COMMUNICATION DIVISION',
        'COMPLIANCE',
        'INTERNAL AUDIT DIVISION',
        'CORPORATE SOCIAL RESPONSIBILITY DIVISION',
        'CSR',
        'REVEGETASI',
        'NURSERY & RND',
        'EKSPLORASI',
    ],

    'Strategy / Business' => [
        'BUSINESS IMPROVEMENT & SIPM DIVISION',
        'BUSINESS UNIT',
        'Business Unit',
        'Business Service Division',
        'STRATEGY & PERFORMANCE MGMT OFFICE DIVISION',
        'GMO STRATEGIC MINE PLANNING DIVISION',
    ],

    'Service / Security / Support' => [
        'SERVICE',
        'SERVICE DIVISION',
        'SECURITY',
        'SUPPORT',
        'SITE ADMIN',
        'ADMINISTRATION DIVISION',
        'Administration',
        'SM',
        'TAKA',
        'OTD',
        'PACKMEAL',
        'KITCHEN',
        'Catering Division',
        'Sampler All Division',
        'Survey',
        'Surveyor All Division',
        'TRANSPORTASI',
        'A2B',
    ],

    'Pendidikan / Magang' => [
        'POLTEK',
        'Politeknik Sinar Mas Berau Coal',
        'KAMPUS MERDEKA',
        'Dosen',
        'Magang',
        'Internship Student',
        'PRAKERIN PKL TA',
        'Helper',
        'Karyawan',
        'TENAGA AHLI',
        'SECTION HEAD',
        'Operator Line Boring',
        'Driver',
        'Driver All Division',
    ],

    'Tidak spesifik / All Divisi' => [
        'ALL DEVISI',
        'ALL DIVISI',
        'ALL DIVISION',
        'ALL Divise',
        'ALL Divisi',
        'All DIVISI',
        'All Devition',
        'All Divisi',
        'All Division',
        'All Divison',
        'All divisi',
        '-',
    ],

    'Eksternal / Vendor / Lokasi' => [
        'CV. Haryda Oto',
        'PT Surveyor Indonesia',
        'PAMA BRCB',
        'PAMA BRCG',
        'KAMAJU-PAMA',
        'KAMAJU-UT',
        'AMP - EVI',
        'AMP-MTL',
        'KALIMATAN & EAST INDONESIA',
        'NORTHERN KALIMANTAN',
        'MTN BLOK C2HU',
        'MTN Blok 56',
        'MTN Blok 59',
        'MTN Blok C2HU',
        'Integrated service solution',
    ],

];
